#!/usr/bin/env bash
# A script that creates a compressed archive of a MySQL dump.

#  Create a dump of all databases in MySQL
#+ taking root password as argument
mysqldump --all-databases -u root --password="$1" > backup.sql

# Create a compressed archive of dump.
tar -cvzf "$(date +%d-%m-%Y)".tar.gz backup.sql
