#!/usr/bin/env bash
#  This script pings an IP address entered as an argument 5 times
#+ or prints a display message if no IP is passed.

if [ $# -eq 0 ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  ping -c 5 "$1"
fi
