#!/bin/bash
# A script to install and reconfigure nginx to port 80

sudo nano /etc/nginx/nginx.conf
sudo sed -i 's/listen [0-9]\{1,5\};/listen 80;/' /etc/nginx/nginx.conf
sudo systemctl restart nginx

