#!/usr/bin/env bash
#  This script displays Best School ten times,
#+ displays it with a Hi on the 9th time.
n=1
while [ $n -lt 10 ]
do
	if [[ $n == 9 ]]; then
		echo "Hi"
	fi
	echo "Best School"
	((n++))
done
