#!/usr/bin/env bash
#  This script displays time with a while loop

hour=0

while [ $hour -lt 13 ]
do
  echo "Hour: $hour"
  minute=1
  while [ $minute -le 59 ]
  do
    echo "$minute"
    (( minute++ ))
  done
  (( hour++ ))
done
